<a href="https://colab.research.google.com/github/cylaadhan/FuzzyLogic/blob/main/TAsaya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload file Excel
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file
# =========================
df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom yang dipakai
# =========================
kolom_dipakai = [
    "Standar",
    "Pernyataan Isi Standar",
    "Pernyataan Standar Indikator",
    "FULL"
]

# Cek apakah semua kolom ada
for kolom in kolom_dipakai:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file Excel.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Fungsi Case Folding
# Case folding = mengubah huruf besar menjadi huruf kecil
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 6. Buat tabel output
# Kolom asli tetap dipertahankan
# Case folding hanya dari kolom FULL
# =========================
tabel_case_folding = pd.DataFrame()

tabel_case_folding["No"] = range(1, len(df) + 1)
tabel_case_folding["Standar"] = df["Standar"]
tabel_case_folding["Pernyataan Isi Standar"] = df["Pernyataan Isi Standar"]
tabel_case_folding["Pernyataan Standar Indikator"] = df["Pernyataan Standar Indikator"]
tabel_case_folding["FULL"] = df["FULL"]
tabel_case_folding["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 7. Ringkasan hasil
# =========================
jumlah_data = len(tabel_case_folding)

jumlah_berubah = (
    tabel_case_folding["FULL"].apply(teks_aman)
    != tabel_case_folding["Hasil Case Folding FULL"]
).sum()

print("\nHASIL CASE FOLDING KOLOM FULL")
print("Jumlah data:", jumlah_data)
print("Jumlah data FULL yang berubah:", jumlah_berubah)
print("Jumlah data FULL yang tidak berubah:", jumlah_data - jumlah_berubah)

# =========================
# 8. Tampilkan preview tabel
# =========================
display(
    tabel_case_folding.head(10).style
    .set_caption("Tabel Hasil Preprocessing Tahap Case Folding")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 9. Simpan ke CSV
# =========================
output_file = "casefolding.csv"

tabel_case_folding.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 10. Download file CSV
# =========================
files.download(output_file)

Saving standarbersih.xlsx to standarbersih.xlsx
Kolom dalam file:
['Standar', 'Pernyataan Isi Standar', 'Pernyataan Standar Indikator', 'FULL']

HASIL CASE FOLDING KOLOM FULL
Jumlah data: 373
Jumlah data FULL yang berubah: 373
Jumlah data FULL yang tidak berubah: 0

File CSV berhasil dibuat: casefolding.csv

In [15]:
import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload file Excel / CSV
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Cek kolom yang dibutuhkan
# =========================
kolom_wajib = [
    "Standar",
    "Pernyataan Isi Standar",
    "Pernyataan Standar Indikator",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 6. Cleansing
# Membersihkan:
# - &nbsp;
# - non-breaking space
# - enter / line break
# - tab
# - spasi ganda
#
# Tidak menghapus tanda baca.
# Tidak melakukan strip.
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

# =========================
# 7. Ambil kata sebelum dan sesudah bagian yang diganti
# =========================
def ambil_konteks(teks, start, end):
    sebelum = teks[:start]
    sesudah = teks[end:]

    kata_sebelum = re.findall(r"\b\w+\b", sebelum)
    kata_sesudah = re.findall(r"\b\w+\b", sesudah)

    kata_kiri = kata_sebelum[-1] if len(kata_sebelum) > 0 else "awal teks"
    kata_kanan = kata_sesudah[0] if len(kata_sesudah) > 0 else "akhir teks"

    return kata_kiri, kata_kanan

# =========================
# 8. Cek detail perubahan cleansing
# =========================
def detail_perubahan_cleansing(teks_sebelum, teks_sesudah):
    teks_sebelum = teks_aman(teks_sebelum)
    teks_sesudah = teks_aman(teks_sesudah)

    jenis_perubahan = []
    bagian_diganti = []

    # Cek &nbsp;
    for match in re.finditer(r"&nbsp;", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "&nbsp; diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("&nbsp; diubah menjadi spasi")

        bagian_diganti.append(
            f"&nbsp; setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek non-breaking space asli
    for match in re.finditer("\xa0", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "non-breaking space diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("non-breaking space diubah menjadi spasi")

        bagian_diganti.append(
            f"non-breaking space setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek enter / line break \n
    for match in re.finditer(r"\n", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "enter / line break diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("enter / line break diubah menjadi spasi")

        bagian_diganti.append(
            f"enter / line break setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek carriage return \r
    for match in re.finditer(r"\r", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "carriage return diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("carriage return diubah menjadi spasi")

        bagian_diganti.append(
            f"carriage return setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek tab \t
    for match in re.finditer(r"\t", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "tab diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("tab diubah menjadi spasi")

        bagian_diganti.append(
            f"tab setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek spasi ganda
    for match in re.finditer(r" {2,}", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())
        jumlah_spasi = len(match.group())

        if "spasi ganda dirapikan menjadi satu spasi" not in jenis_perubahan:
            jenis_perubahan.append("spasi ganda dirapikan menjadi satu spasi")

        bagian_diganti.append(
            f"{jumlah_spasi} spasi setelah kata '{kiri}' sebelum kata '{kanan}' dirapikan menjadi satu spasi"
        )

    if teks_sebelum == teks_sesudah:
        return "Tidak ada perubahan", "Tidak ada perubahan"

    if len(jenis_perubahan) == 0:
        return "Teks berubah setelah cleansing", "Perubahan terjadi setelah proses cleansing"

    return "; ".join(jenis_perubahan), "; ".join(bagian_diganti)

# =========================
# 9. Proses Case Folding dan Cleansing
# =========================
hasil_case_folding = df["FULL"].apply(case_folding)
hasil_cleansing = hasil_case_folding.apply(cleansing)

# =========================
# 10. Buat kolom keterangan perubahan
# =========================
kolom_yang_berubah = []
apa_yang_diubah = []
bagian_yang_diganti = []

for sebelum, sesudah in zip(hasil_case_folding, hasil_cleansing):
    jenis, bagian = detail_perubahan_cleansing(sebelum, sesudah)

    if jenis == "Tidak ada perubahan":
        kolom_yang_berubah.append("Tidak ada")
        apa_yang_diubah.append("Tidak ada perubahan")
        bagian_yang_diganti.append("Tidak ada perubahan")
    else:
        kolom_yang_berubah.append("FULL")
        apa_yang_diubah.append(jenis)
        bagian_yang_diganti.append(bagian)

# =========================
# 11. Buat tabel output
# =========================
tabel_cleansing = pd.DataFrame()

tabel_cleansing["No"] = range(1, len(df) + 1)
tabel_cleansing["Standar"] = df["Standar"]
tabel_cleansing["Pernyataan Isi Standar"] = df["Pernyataan Isi Standar"]
tabel_cleansing["Pernyataan Standar Indikator"] = df["Pernyataan Standar Indikator"]
tabel_cleansing["FULL"] = df["FULL"]
tabel_cleansing["Hasil Case Folding FULL"] = hasil_case_folding
tabel_cleansing["Hasil Cleansing FULL"] = hasil_cleansing
tabel_cleansing["Kolom yang Berubah"] = kolom_yang_berubah
tabel_cleansing["Apa yang Diubah"] = apa_yang_diubah
tabel_cleansing["Bagian yang Diganti"] = bagian_yang_diganti

# =========================
# 12. Ringkasan hasil
# =========================
jumlah_data = len(tabel_cleansing)

jumlah_case_folding_berubah = (
    tabel_cleansing["FULL"].apply(teks_aman)
    != tabel_cleansing["Hasil Case Folding FULL"]
).sum()

jumlah_cleansing_berubah = (
    tabel_cleansing["Hasil Case Folding FULL"]
    != tabel_cleansing["Hasil Cleansing FULL"]
).sum()

print("\nHASIL PREPROCESSING CLEANSING")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah case folding:", jumlah_case_folding_berubah)
print("Jumlah data berubah setelah cleansing:", jumlah_cleansing_berubah)

# =========================
# 13. Preview tabel
# =========================
display(
    tabel_cleansing.head(10).style
    .set_caption("Tabel Hasil Preprocessing Tahap Cleansing")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 14. Simpan ke CSV
# =========================
output_file = "cleansing.csv"

tabel_cleansing.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 15. Download file CSV
# =========================
files.download(output_file)

Saving standarbersih.xlsx to standarbersih (6).xlsx
Kolom dalam file:
['No', 'Standar', 'Pernyataan Isi Standar', 'Pernyataan Standar Indikator', 'FULL']

HASIL PREPROCESSING CLEANSING
Jumlah data: 373
Jumlah data berubah setelah case folding: 373
Jumlah data berubah setelah cleansing: 110

File CSV berhasil dibuat: cleansing.csv

In [17]:
import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload data standar asli
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom wajib dari data standar
# =========================
kolom_wajib = [
    "Standar",
    "Pernyataan Isi Standar",
    "Pernyataan Standar Indikator",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# Mengubah huruf besar menjadi huruf kecil
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 6. Cleansing
# Membersihkan:
# - &nbsp;
# - non-breaking space
# - enter / line break
# - tab
# - spasi ganda
#
# Catatan:
# Di sini belum dilakukan strip.
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

# =========================
# 7. Strip
# Menghapus spasi di awal dan akhir teks
# Input strip diambil dari hasil cleansing
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

# =========================
# 8. Fungsi ambil kata awal dan akhir
# =========================
def kata_awal(teks):
    teks_bersih = teks.strip()
    kata = re.findall(r"\b\w+\b", teks_bersih)
    return kata[0] if len(kata) > 0 else "teks kosong"

def kata_akhir(teks):
    teks_bersih = teks.strip()
    kata = re.findall(r"\b\w+\b", teks_bersih)
    return kata[-1] if len(kata) > 0 else "teks kosong"

# =========================
# 9. Cek detail perubahan strip
# Dibandingkan dari:
# Hasil Cleansing FULL → Hasil Strip FULL
# =========================
def detail_perubahan_strip(teks_sebelum, teks_sesudah):
    teks_sebelum = teks_aman(teks_sebelum)
    teks_sesudah = teks_aman(teks_sesudah)

    if teks_sebelum == teks_sesudah:
        return "Tidak ada", "Tidak ada perubahan", "Tidak ada perubahan"

    perubahan = []
    bagian = []

    jumlah_spasi_awal = len(teks_sebelum) - len(teks_sebelum.lstrip())
    jumlah_spasi_akhir = len(teks_sebelum) - len(teks_sebelum.rstrip())

    if jumlah_spasi_awal > 0:
        perubahan.append("spasi awal teks dihapus")
        bagian.append(
            f"{jumlah_spasi_awal} spasi di awal teks sebelum kata '{kata_awal(teks_sebelum)}' dihapus"
        )

    if jumlah_spasi_akhir > 0:
        perubahan.append("spasi akhir teks dihapus")
        bagian.append(
            f"{jumlah_spasi_akhir} spasi di akhir teks setelah kata '{kata_akhir(teks_sebelum)}' dihapus"
        )

    if len(perubahan) == 0:
        return "FULL", "Teks berubah setelah strip", "Perubahan terjadi pada spasi awal atau akhir teks"

    return "FULL", "; ".join(perubahan), "; ".join(bagian)

# =========================
# 10. Proses bertahap dari data standar asli
# FULL asli
# ↓
# Case Folding
# ↓
# Cleansing
# ↓
# Strip
# =========================
hasil_case_folding = df["FULL"].apply(case_folding)
hasil_cleansing = hasil_case_folding.apply(cleansing)
hasil_strip = hasil_cleansing.apply(strip_teks)

# =========================
# 11. Buat keterangan perubahan strip
# =========================
kolom_yang_berubah = []
apa_yang_diubah = []
bagian_yang_diganti = []

for sebelum, sesudah in zip(hasil_cleansing, hasil_strip):
    kolom, apa, bagian = detail_perubahan_strip(sebelum, sesudah)

    kolom_yang_berubah.append(kolom)
    apa_yang_diubah.append(apa)
    bagian_yang_diganti.append(bagian)

# =========================
# 12. Buat tabel output
# =========================
tabel_strip = pd.DataFrame()

tabel_strip["No"] = range(1, len(df) + 1)
tabel_strip["Standar"] = df["Standar"]
tabel_strip["Pernyataan Isi Standar"] = df["Pernyataan Isi Standar"]
tabel_strip["Pernyataan Standar Indikator"] = df["Pernyataan Standar Indikator"]
tabel_strip["FULL"] = df["FULL"]
tabel_strip["Hasil Case Folding FULL"] = hasil_case_folding
tabel_strip["Hasil Cleansing FULL"] = hasil_cleansing
tabel_strip["Hasil Strip FULL"] = hasil_strip
tabel_strip["Kolom yang Berubah"] = kolom_yang_berubah
tabel_strip["Apa yang Diubah"] = apa_yang_diubah
tabel_strip["Bagian yang Diganti"] = bagian_yang_diganti

# =========================
# 13. Ringkasan hasil
# =========================
jumlah_data = len(tabel_strip)

jumlah_case_folding_berubah = (
    tabel_strip["FULL"].apply(teks_aman)
    != tabel_strip["Hasil Case Folding FULL"]
).sum()

jumlah_cleansing_berubah = (
    tabel_strip["Hasil Case Folding FULL"]
    != tabel_strip["Hasil Cleansing FULL"]
).sum()

jumlah_strip_berubah = (
    tabel_strip["Hasil Cleansing FULL"]
    != tabel_strip["Hasil Strip FULL"]
).sum()

print("\nHASIL PREPROCESSING STRIP")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah case folding:", jumlah_case_folding_berubah)
print("Jumlah data berubah setelah cleansing:", jumlah_cleansing_berubah)
print("Jumlah data berubah setelah strip:", jumlah_strip_berubah)

# =========================
# 14. Preview tabel
# =========================
display(
    tabel_strip.head(10).style
    .set_caption("Tabel Hasil Preprocessing Tahap Strip")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 15. Simpan ke CSV
# =========================
output_file = "strip.csv"

tabel_strip.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 16. Download CSV
# =========================
files.download(output_file)

Saving standarbersih.xlsx to standarbersih (8).xlsx
Kolom dalam file:
['No', 'Standar', 'Pernyataan Isi Standar', 'Pernyataan Standar Indikator', 'FULL']

HASIL PREPROCESSING STRIP
Jumlah data: 373
Jumlah data berubah setelah case folding: 373
Jumlah data berubah setelah cleansing: 110
Jumlah data berubah setelah strip: 0

File CSV berhasil dibuat: strip.csv

In [18]:
import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload data standar asli
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom wajib
# =========================
kolom_wajib = [
    "Standar",
    "Pernyataan Isi Standar",
    "Pernyataan Standar Indikator",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 6. Cleansing
# Membersihkan:
# - &nbsp;
# - non-breaking space
# - enter / line break
# - tab
# - spasi ganda
# Belum strip.
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

# =========================
# 7. Strip
# Menghapus spasi awal dan akhir teks
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

# =========================
# 8. Ambil konteks kata sebelum dan sesudah
# =========================
def ambil_konteks(teks, start, end):
    sebelum = teks[:start]
    sesudah = teks[end:]

    kata_sebelum = re.findall(r"\b\w+\b", sebelum)
    kata_sesudah = re.findall(r"\b\w+\b", sesudah)

    kata_kiri = kata_sebelum[-1] if len(kata_sebelum) > 0 else "awal teks"
    kata_kanan = kata_sesudah[0] if len(kata_sesudah) > 0 else "akhir teks"

    return kata_kiri, kata_kanan

# =========================
# 9. Punctuation Removal
# Menghapus:
# - titik koma ;
# - titik . di akhir kalimat
#
# Catatan:
# - Titik dua : tidak dihapus
# - Titik di tengah angka/kata tidak dihapus
# =========================
def punctuation_removal(teks):
    teks = teks_aman(teks)

    # Hapus titik koma
    teks = teks.replace(";", " ")

    # Hapus titik yang berada di akhir kalimat
    # Pola ini menghapus titik yang diikuti spasi atau akhir teks
    teks = re.sub(r"\.(?=\s|$)", "", teks)

    # Rapikan spasi setelah penghapusan tanda baca
    teks = re.sub(r"\s+", " ", teks).strip()

    return teks

# =========================
# 10. Detail perubahan punctuation removal
# =========================
def detail_perubahan_punctuation(teks_sebelum, teks_sesudah):
    teks_sebelum = teks_aman(teks_sebelum)
    teks_sesudah = teks_aman(teks_sesudah)

    if teks_sebelum == teks_sesudah:
        return "Tidak ada", "Tidak ada perubahan", "Tidak ada perubahan"

    jenis_perubahan = []
    bagian_diganti = []

    # Cek titik koma ;
    for match in re.finditer(r";", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "titik koma dihapus" not in jenis_perubahan:
            jenis_perubahan.append("titik koma dihapus")

        bagian_diganti.append(
            f"titik koma ';' setelah kata '{kiri}' sebelum kata '{kanan}' dihapus"
        )

    # Cek titik di akhir kalimat
    for match in re.finditer(r"\.(?=\s|$)", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "titik di akhir kalimat dihapus" not in jenis_perubahan:
            jenis_perubahan.append("titik di akhir kalimat dihapus")

        if kanan == "akhir teks":
            bagian_diganti.append(
                f"titik '.' setelah kata '{kiri}' di akhir teks dihapus"
            )
        else:
            bagian_diganti.append(
                f"titik '.' setelah kata '{kiri}' sebelum kata '{kanan}' dihapus"
            )

    if len(jenis_perubahan) == 0:
        return "FULL", "Teks berubah setelah punctuation removal", "Perubahan terjadi pada tanda baca"

    return "FULL", "; ".join(jenis_perubahan), "; ".join(bagian_diganti)

# =========================
# 11. Proses bertahap dari data standar asli
# FULL asli
# ↓
# Case Folding
# ↓
# Cleansing
# ↓
# Strip
# ↓
# Punctuation Removal
# =========================
hasil_case_folding = df["FULL"].apply(case_folding)
hasil_cleansing = hasil_case_folding.apply(cleansing)
hasil_strip = hasil_cleansing.apply(strip_teks)
hasil_punctuation = hasil_strip.apply(punctuation_removal)

# =========================
# 12. Buat keterangan perubahan punctuation removal
# =========================
kolom_yang_berubah = []
apa_yang_diubah = []
bagian_yang_diganti = []

for sebelum, sesudah in zip(hasil_strip, hasil_punctuation):
    kolom, apa, bagian = detail_perubahan_punctuation(sebelum, sesudah)

    kolom_yang_berubah.append(kolom)
    apa_yang_diubah.append(apa)
    bagian_yang_diganti.append(bagian)

# =========================
# 13. Buat tabel output
# =========================
tabel_punctuation = pd.DataFrame()

tabel_punctuation["No"] = range(1, len(df) + 1)
tabel_punctuation["Standar"] = df["Standar"]
tabel_punctuation["Pernyataan Isi Standar"] = df["Pernyataan Isi Standar"]
tabel_punctuation["Pernyataan Standar Indikator"] = df["Pernyataan Standar Indikator"]
tabel_punctuation["FULL"] = df["FULL"]
tabel_punctuation["Hasil Case Folding FULL"] = hasil_case_folding
tabel_punctuation["Hasil Cleansing FULL"] = hasil_cleansing
tabel_punctuation["Hasil Strip FULL"] = hasil_strip
tabel_punctuation["Hasil Punctuation Removal FULL"] = hasil_punctuation
tabel_punctuation["Kolom yang Berubah"] = kolom_yang_berubah
tabel_punctuation["Apa yang Diubah"] = apa_yang_diubah
tabel_punctuation["Bagian yang Diganti"] = bagian_yang_diganti

# =========================
# 14. Ringkasan hasil
# =========================
jumlah_data = len(tabel_punctuation)

jumlah_punctuation_berubah = (
    tabel_punctuation["Hasil Strip FULL"].apply(teks_aman)
    != tabel_punctuation["Hasil Punctuation Removal FULL"].apply(teks_aman)
).sum()

print("\nHASIL PUNCTUATION REMOVAL")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah punctuation removal:", jumlah_punctuation_berubah)
print("Jumlah data tidak berubah:", jumlah_data - jumlah_punctuation_berubah)
print("Yang dihapus: titik koma ';' dan titik '.' di akhir kalimat")
print("Yang tidak dihapus: titik dua ':'")

# =========================
# 15. Preview tabel
# =========================
display(
    tabel_punctuation.head(10).style
    .set_caption("Tabel Hasil Preprocessing Tahap Punctuation Removal")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 16. Simpan ke CSV
# =========================
output_file = "punctuationremoval.csv"

tabel_punctuation.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 17. Download CSV
# =========================
files.download(output_file)

Saving standarbersih.xlsx to standarbersih (9).xlsx
Kolom dalam file:
['No', 'Standar', 'Pernyataan Isi Standar', 'Pernyataan Standar Indikator', 'FULL']

HASIL PUNCTUATION REMOVAL
Jumlah data: 373
Jumlah data berubah setelah punctuation removal: 340
Jumlah data tidak berubah: 33
Yang dihapus: titik koma ';' dan titik '.' di akhir kalimat
Yang tidak dihapus: titik dua ':'

File CSV berhasil dibuat: punctuationremoval.csv

In [19]:
# =========================
# 1. Install library
# =========================
!pip install transformers -q

import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display
from transformers import AutoTokenizer

# =========================
# 2. Upload data standar asli
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 3. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 4. Kolom wajib
# =========================
kolom_wajib = [
    "Standar",
    "Pernyataan Isi Standar",
    "Pernyataan Standar Indikator",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file.")

# =========================
# 5. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 6. Case Folding
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 7. Cleansing
# Membersihkan:
# - &nbsp;
# - non-breaking space
# - enter / line break
# - tab
# - spasi ganda
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

# =========================
# 8. Strip
# Menghapus spasi awal dan akhir teks
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

# =========================
# 9. Punctuation Removal
# Menghapus:
# - titik koma ;
# - titik . di akhir kalimat
#
# Tidak menghapus titik dua :
# =========================
def punctuation_removal(teks):
    teks = teks_aman(teks)

    # Hapus titik koma
    teks = teks.replace(";", " ")

    # Hapus titik yang berada di akhir kalimat atau akhir teks
    teks = re.sub(r"\.(?=\s|$)", "", teks)

    # Rapikan spasi
    teks = re.sub(r"\s+", " ", teks).strip()

    return teks

# =========================
# 10. Load tokenizer IndoBERT
# =========================
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

# =========================
# 11. Tokenisasi IndoBERT
# Menggunakan special token:
# [CLS] di awal
# [SEP] di akhir
# =========================
def tokenisasi_indobert(teks):
    teks = teks_aman(teks)

    encoded = tokenizer.encode(
        teks,
        add_special_tokens=True,   # menambahkan [CLS] dan [SEP]
        truncation=True,
        max_length=512
    )

    tokens = tokenizer.convert_ids_to_tokens(encoded)

    # Pemisah token menggunakan koma
    return ", ".join(tokens)

# =========================
# 12. Proses bertahap
# FULL asli
# ↓
# Case Folding
# ↓
# Cleansing
# ↓
# Strip
# ↓
# Punctuation Removal
# ↓
# Tokenisasi IndoBERT
# =========================
hasil_case_folding = df["FULL"].apply(case_folding)
hasil_cleansing = hasil_case_folding.apply(cleansing)
hasil_strip = hasil_cleansing.apply(strip_teks)
hasil_punctuation = hasil_strip.apply(punctuation_removal)
hasil_tokenisasi = hasil_punctuation.apply(tokenisasi_indobert)

# =========================
# 13. Buat tabel output
# =========================
tabel_tokenisasi = pd.DataFrame()

tabel_tokenisasi["No"] = range(1, len(df) + 1)
tabel_tokenisasi["Standar"] = df["Standar"]
tabel_tokenisasi["Pernyataan Isi Standar"] = df["Pernyataan Isi Standar"]
tabel_tokenisasi["Pernyataan Standar Indikator"] = df["Pernyataan Standar Indikator"]
tabel_tokenisasi["FULL"] = df["FULL"]
tabel_tokenisasi["Hasil Case Folding FULL"] = hasil_case_folding
tabel_tokenisasi["Hasil Cleansing FULL"] = hasil_cleansing
tabel_tokenisasi["Hasil Strip FULL"] = hasil_strip
tabel_tokenisasi["Hasil Punctuation Removal FULL"] = hasil_punctuation
tabel_tokenisasi["Tokenisasi IndoBERT FULL"] = hasil_tokenisasi

# =========================
# 14. Ringkasan hasil
# =========================
print("\nHASIL TOKENISASI INDOBERT")
print("Jumlah data:", len(tabel_tokenisasi))
print("Tokenizer: indobenchmark/indobert-base-p1")
print("Token khusus yang digunakan: [CLS] dan [SEP]")
print("Input tokenisasi dari kolom: Hasil Punctuation Removal FULL")

# =========================
# 15. Preview tabel
# =========================
display(
    tabel_tokenisasi.head(10).style
    .set_caption("Tabel Hasil Tokenisasi Menggunakan IndoBERT")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 16. Simpan ke CSV
# =========================
output_file = "tokenisasi_indobert.csv"

tabel_tokenisasi.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 17. Download CSV
# =========================
files.download(output_file)

Saving standarbersih.xlsx to standarbersih (10).xlsx
Kolom dalam file:
['No', 'Standar', 'Pernyataan Isi Standar', 'Pernyataan Standar Indikator', 'FULL']

HASIL TOKENISASI INDOBERT
Jumlah data: 373
Tokenizer: indobenchmark/indobert-base-p1
Token khusus yang digunakan: [CLS] dan [SEP]
Input tokenisasi dari kolom: Hasil Punctuation Removal FULL

File CSV berhasil dibuat: tokenisasi_indobert.csv

In [1]:
# =========================
# 1. Install library
# =========================
!pip install transformers -q

import pandas as pd
import re
import html
import torch
import numpy as np
from google.colab import files
from IPython.display import display
from transformers import AutoTokenizer, AutoModel

# =========================
# 2. Upload data standar asli
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 3. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 4. Kolom wajib
# =========================
kolom_wajib = [
    "Standar",
    "Pernyataan Isi Standar",
    "Pernyataan Standar Indikator",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file.")

# =========================
# 5. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 6. Case Folding
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 7. Cleansing
# Membersihkan:
# - &nbsp;
# - non-breaking space
# - enter / line break
# - tab
# - spasi ganda
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

# =========================
# 8. Strip
# Menghapus spasi awal dan akhir teks
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

# =========================
# 9. Punctuation Removal
# Menghapus:
# - titik koma ;
# - titik . di akhir kalimat
# Tidak menghapus titik dua :
# =========================
def punctuation_removal(teks):
    teks = teks_aman(teks)

    teks = teks.replace(";", " ")
    teks = re.sub(r"\.(?=\s|$)", "", teks)
    teks = re.sub(r"\s+", " ", teks).strip()

    return teks

# =========================
# 10. Load tokenizer dan model IndoBERT
# =========================
model_name = "indobenchmark/indobert-base-p1"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("Device yang digunakan:", device)

# =========================
# 11. Tokenisasi IndoBERT
# Menggunakan [CLS] dan [SEP]
# =========================
def tokenisasi_indobert(teks):
    teks = teks_aman(teks)

    encoded = tokenizer.encode(
        teks,
        add_special_tokens=True,
        truncation=True,
        max_length=512
    )

    tokens = tokenizer.convert_ids_to_tokens(encoded)

    return ", ".join(tokens)

# =========================
# 12. Ekstraksi fitur teks menggunakan IndoBERT
# Output: vektor embedding dari token [CLS]
# =========================
def ekstraksi_embedding_cls(teks):
    teks = teks_aman(teks)

    inputs = tokenizer(
        teks,
        return_tensors="pt",
        add_special_tokens=True,
        truncation=True,
        padding="max_length",
        max_length=512
    )

    inputs = {key: value.to(device) for key, value in inputs.items()}

    with torch.no_grad():
        outputs = model(**inputs)

    # last_hidden_state bentuknya:
    # [jumlah_data, jumlah_token, dimensi_embedding]
    last_hidden_state = outputs.last_hidden_state

    # Ambil embedding token [CLS]
    cls_embedding = last_hidden_state[:, 0, :].squeeze().cpu().numpy()

    return cls_embedding

# =========================
# 13. Proses bertahap
# FULL asli
# ↓
# Case Folding
# ↓
# Cleansing
# ↓
# Strip
# ↓
# Punctuation Removal
# ↓
# Tokenisasi IndoBERT
# ↓
# Ekstraksi Fitur / Embedding [CLS]
# =========================
hasil_case_folding = df["FULL"].apply(case_folding)
hasil_cleansing = hasil_case_folding.apply(cleansing)
hasil_strip = hasil_cleansing.apply(strip_teks)
hasil_punctuation = hasil_strip.apply(punctuation_removal)
hasil_tokenisasi = hasil_punctuation.apply(tokenisasi_indobert)

# Ekstraksi embedding
embedding_list = []

for teks in hasil_punctuation:
    embedding = ekstraksi_embedding_cls(teks)
    embedding_list.append(embedding)

embedding_array = np.vstack(embedding_list)

# Ubah embedding menjadi string agar bisa disimpan ke CSV
embedding_string = [
    ", ".join([str(round(nilai, 6)) for nilai in vector])
    for vector in embedding_array
]

# =========================
# 14. Buat tabel output
# =========================
tabel_embedding = pd.DataFrame()

tabel_embedding["No"] = range(1, len(df) + 1)
tabel_embedding["Standar"] = df["Standar"]
tabel_embedding["Pernyataan Isi Standar"] = df["Pernyataan Isi Standar"]
tabel_embedding["Pernyataan Standar Indikator"] = df["Pernyataan Standar Indikator"]
tabel_embedding["FULL"] = df["FULL"]
tabel_embedding["Hasil Case Folding FULL"] = hasil_case_folding
tabel_embedding["Hasil Cleansing FULL"] = hasil_cleansing
tabel_embedding["Hasil Strip FULL"] = hasil_strip
tabel_embedding["Hasil Punctuation Removal FULL"] = hasil_punctuation
tabel_embedding["Tokenisasi IndoBERT FULL"] = hasil_tokenisasi
tabel_embedding["Vektor Embedding CLS FULL"] = embedding_string
tabel_embedding["Dimensi Embedding"] = embedding_array.shape[1]

# =========================
# 15. Ringkasan hasil
# =========================
print("\nHASIL EKSTRAKSI FITUR TEKS MENGGUNAKAN INDOBERT")
print("Jumlah data:", len(tabel_embedding))
print("Model:", model_name)
print("Representasi embedding yang digunakan: token [CLS]")
print("Dimensi embedding:", embedding_array.shape[1])
print("Bentuk array embedding:", embedding_array.shape)

# =========================
# 16. Preview tabel
# =========================
display(
    tabel_embedding.head(5).style
    .set_caption("Tabel Hasil Ekstraksi Fitur Teks Menggunakan IndoBERT")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 17. Simpan ke CSV
# =========================
output_csv = "ekstraksi_fitur.csv"

tabel_embedding.to_csv(
    output_csv,
    index=False,
    encoding="utf-8-sig"
)

# =========================
# 18. Simpan embedding asli ke file NPY
# Ini penting untuk cosine similarity
# =========================
output_npy = "embedding_indobert.npy"
np.save(output_npy, embedding_array)

print("\nFile CSV berhasil dibuat:", output_csv)
print("File embedding NPY berhasil dibuat:", output_npy)

# =========================
# 19. Download file
# =========================
files.download(output_csv)
files.download(output_npy)

Saving standarbersih.xlsx to standarbersih.xlsx
Kolom dalam file:
['No', 'Standar', 'Pernyataan Isi Standar', 'Pernyataan Standar Indikator', 'FULL']

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/229k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/498M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Device yang digunakan: cpu

model.safetensors:   0%|          | 0.00/498M [00:00<?, ?B/s]

HASIL EKSTRAKSI FITUR TEKS MENGGUNAKAN INDOBERT
Jumlah data: 373
Model: indobenchmark/indobert-base-p1
Representasi embedding yang digunakan: token [CLS]
Dimensi embedding: 768
Bentuk array embedding: (373, 768)

File CSV berhasil dibuat: ekstraksi_fitur.csv
File embedding NPY berhasil dibuat: embedding_indobert.npy

In [3]:
import pandas as pd
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload data matrik asli
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom wajib data matrik
# =========================
kolom_wajib = [
    "KRITERIA",  # Changed from 'Kriteria'
    "ELEMEN",    # Changed from 'Elemen'
    "DESKRIPTOR",# Changed from 'Deskriptor'
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file matrik kamu.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# Mengubah huruf besar menjadi huruf kecil
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

# =========================
# 6. Buat tabel output
# =========================
tabel_case_folding = pd.DataFrame()

tabel_case_folding["No"] = range(1, len(df) + 1)
tabel_case_folding["Kriteria"] = df["KRITERIA"] # Changed to 'KRITERIA'
tabel_case_folding["Elemen"] = df["ELEMEN"]     # Changed to 'ELEMEN'
tabel_case_folding["Deskriptor"] = df["DESKRIPTOR"] # Changed to 'DESKRIPTOR'
tabel_case_folding["FULL"] = df["FULL"]
tabel_case_folding["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 7. Ringkasan hasil
# =========================
jumlah_data = len(tabel_case_folding)

jumlah_berubah = (
    tabel_case_folding["FULL"].apply(teks_aman)
    != tabel_case_folding["Hasil Case Folding FULL"]
).sum()

print("\nHASIL CASE FOLDING DATA MATRIK")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah case folding:", jumlah_berubah)
print("Jumlah data tidak berubah:", jumlah_data - jumlah_berubah)

# =========================
# 8. Preview tabel
# =========================
display(
    tabel_case_folding.head(10).style
    .set_caption("Tabel Hasil Preprocessing Data Matrik Tahap Case Folding")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 9. Simpan ke CSV
# =========================
output_file = "casefoldingmatrik.csv"

tabel_case_folding.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 10. Download CSV
# =========================
files.download(output_file)

Saving matrik.xlsx to matrik (1).xlsx
Kolom dalam file:
['KRITERIA', 'ELEMEN', 'DESKRIPTOR', 'FULL']

HASIL CASE FOLDING DATA MATRIK
Jumlah data: 75
Jumlah data berubah setelah case folding: 75
Jumlah data tidak berubah: 0

File CSV berhasil dibuat: casefoldingmatrik.csv

In [5]:
import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload data matrik
# Bisa upload data asli atau file hasil case folding
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom wajib data matrik
# =========================
kolom_wajib = [
    "KRITERIA", # Changed from 'Kriteria'
    "ELEMEN",   # Changed from 'Elemen'
    "DESKRIPTOR", # Changed from 'Deskriptor'
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file matrik kamu.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# Kalau file yang diupload belum punya kolom hasil case folding,
# maka kolom ini akan dibuat otomatis.
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

if "Hasil Case Folding FULL" not in df.columns:
    df["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 6. Cleansing
# Membersihkan:
# - &nbsp;
# - non-breaking space
# - enter / line break
# - tab
# - spasi ganda
#
# Tidak menghapus tanda baca.
# Tidak melakukan strip.
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

# =========================
# 7. Ambil konteks kata sebelum dan sesudah bagian yang diganti
# =========================
def ambil_konteks(teks, start, end):
    sebelum = teks[:start]
    sesudah = teks[end:]

    kata_sebelum = re.findall(r"\b\w+\b", sebelum)
    kata_sesudah = re.findall(r"\b\w+\b", sesudah)

    kata_kiri = kata_sebelum[-1] if len(kata_sebelum) > 0 else "awal teks"
    kata_kanan = kata_sesudah[0] if len(kata_sesudah) > 0 else "akhir teks"

    return kata_kiri, kata_kanan

# =========================
# 8. Detail perubahan cleansing
# Dibandingkan dari:
# Hasil Case Folding FULL → Hasil Cleansing FULL
# =========================
def detail_perubahan_cleansing(teks_sebelum, teks_sesudah):
    teks_sebelum = teks_aman(teks_sebelum)
    teks_sesudah = teks_aman(teks_sesudah)

    if teks_sebelum == teks_sesudah:
        return "Tidak ada", "Tidak ada perubahan", "Tidak ada perubahan"

    jenis_perubahan = []
    bagian_diganti = []

    # Cek &nbsp;
    for match in re.finditer(r"&nbsp;", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "&nbsp; diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("&nbsp; diubah menjadi spasi")

        bagian_diganti.append(
            f"&nbsp; setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek non-breaking space
    for match in re.finditer("\xa0", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "non-breaking space diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("non-breaking space diubah menjadi spasi")

        bagian_diganti.append(
            f"non-breaking space setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek enter / line break
    for match in re.finditer(r"\n", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "enter / line break diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("enter / line break diubah menjadi spasi")

        bagian_diganti.append(
            f"enter / line break setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek carriage return
    for match in re.finditer(r"\r", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "carriage return diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("carriage return diubah menjadi spasi")

        bagian_diganti.append(
            f"carriage return setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek tab
    for match in re.finditer(r"\t", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "tab diubah menjadi spasi" not in jenis_perubahan:
            jenis_perubahan.append("tab diubah menjadi spasi")

        bagian_diganti.append(
            f"tab setelah kata '{kiri}' sebelum kata '{kanan}' diubah menjadi spasi"
        )

    # Cek spasi ganda
    for match in re.finditer(r" {2,}", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())
        jumlah_spasi = len(match.group())

        if "spasi ganda dirapikan menjadi satu spasi" not in jenis_perubahan:
            jenis_perubahan.append("spasi ganda dirapikan menjadi satu spasi")

        bagian_diganti.append(
            f"{jumlah_spasi} spasi setelah kata '{kiri}' sebelum kata '{kanan}' dirapikan menjadi satu spasi"
        )

    if len(jenis_perubahan) == 0:
        return "FULL", "Teks berubah setelah cleansing", "Perubahan terjadi setelah proses cleansing"

    return "FULL", "; ".join(jenis_perubahan), "; ".join(bagian_diganti)

# =========================
# 9. Proses cleansing
# Input cleansing diambil dari Hasil Case Folding FULL
# =========================
hasil_cleansing = df["Hasil Case Folding FULL"].apply(cleansing)

# =========================
# 10. Buat keterangan perubahan
# =========================
kolom_yang_berubah = []
apa_yang_diubah = []
bagian_yang_diganti = []

for sebelum, sesudah in zip(df["Hasil Case Folding FULL"], hasil_cleansing):
    kolom, apa, bagian = detail_perubahan_cleansing(sebelum, sesudah)

    kolom_yang_berubah.append(kolom)
    apa_yang_diubah.append(apa)
    bagian_yang_diganti.append(bagian)

# =========================
# 11. Buat tabel output
# =========================
tabel_cleansing = pd.DataFrame()

if "No" in df.columns:
    tabel_cleansing["No"] = df["No"]
else:
    tabel_cleansing["No"] = range(1, len(df) + 1)

tabel_cleansing["Kriteria"] = df["KRITERIA"] # Changed to 'KRITERIA'
tabel_cleansing["Elemen"] = df["ELEMEN"]     # Changed to 'ELEMEN'
tabel_cleansing["Deskriptor"] = df["DESKRIPTOR"] # Changed to 'DESKRIPTOR'
tabel_cleansing["FULL"] = df["FULL"]
tabel_cleansing["Hasil Case Folding FULL"] = df["Hasil Case Folding FULL"]
tabel_cleansing["Hasil Cleansing FULL"] = hasil_cleansing
tabel_cleansing["Kolom yang Berubah"] = kolom_yang_berubah
tabel_cleansing["Apa yang Diubah"] = apa_yang_diubah
tabel_cleansing["Bagian yang Diganti"] = bagian_yang_diganti

# =========================
# 12. Ringkasan hasil
# =========================
jumlah_data = len(tabel_cleansing)

jumlah_cleansing_berubah = (
    tabel_cleansing["Hasil Case Folding FULL"].apply(teks_aman)
    != tabel_cleansing["Hasil Cleansing FULL"].apply(teks_aman)
).sum()

print("\nHASIL CLEANSING DATA MATRIK")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah cleansing:", jumlah_cleansing_berubah)
print("Jumlah data tidak berubah:", jumlah_data - jumlah_cleansing_berubah)

# =========================
# 13. Preview tabel
# =========================
display(
    tabel_cleansing.head(10).style
    .set_caption("Tabel Hasil Preprocessing Data Matrik Tahap Cleansing")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 14. Simpan ke CSV
# =========================
output_file = "cleansingmatrik.csv"

tabel_cleansing.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 15. Download CSV
# =========================
files.download(output_file)

Saving matrik.xlsx to matrik (3).xlsx
Kolom dalam file:
['KRITERIA', 'ELEMEN', 'DESKRIPTOR', 'FULL']

HASIL CLEANSING DATA MATRIK
Jumlah data: 75
Jumlah data berubah setelah cleansing: 8
Jumlah data tidak berubah: 67

File CSV berhasil dibuat: cleansingmatrik.csv

In [8]:
import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload file data matrik
# Bisa upload data asli atau file hasil cleansing
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom wajib data matrik
# =========================
kolom_wajib = [
    "KRITERIA", # Corrected from 'Kriteria'
    "ELEMEN",   # Corrected from 'Elemen'
    "DESKRIPTOR", # Corrected from 'Deskriptor'
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file matrik kamu.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# Jika belum ada kolom hasil case folding,
# maka dibuat otomatis
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

if "Hasil Case Folding FULL" not in df.columns:
    df["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 6. Cleansing
# Jika belum ada kolom hasil cleansing,
# maka dibuat otomatis dari Hasil Case Folding FULL
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

if "Hasil Cleansing FULL" not in df.columns:
    df["Hasil Cleansing FULL"] = df["Hasil Case Folding FULL"].apply(cleansing)

# =========================
# 7. Strip
# Menghapus spasi di awal dan akhir teks
# Tidak menghapus tanda baca
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

# =========================
# 8. Fungsi ambil kata awal dan akhir
# =========================
def kata_awal(teks):
    teks_bersih = teks.strip()
    kata = re.findall(r"\b\w+\b", teks_bersih)
    return kata[0] if len(kata) > 0 else "teks kosong"

def kata_akhir(teks):
    teks_bersih = teks.strip()
    kata = re.findall(r"\b\w+\b", teks_bersih)
    return kata[-1] if len(kata) > 0 else "teks kosong"

# =========================
# 9. Detail perubahan strip
# Dibandingkan dari:
# Hasil Cleansing FULL → Hasil Strip FULL
# =========================
def detail_perubahan_strip(teks_sebelum, teks_sesudah):
    teks_sebelum = teks_aman(teks_sebelum)
    teks_sesudah = teks_aman(teks_sesudah)

    if teks_sebelum == teks_sesudah:
        return "Tidak ada", "Tidak ada perubahan", "Tidak ada perubahan"

    perubahan = []
    bagian = []

    jumlah_spasi_awal = len(teks_sebelum) - len(teks_sebelum.lstrip())
    jumlah_spasi_akhir = len(teks_sebelum) - len(teks_sebelum.rstrip())

    if jumlah_spasi_awal > 0:
        perubahan.append("spasi awal teks dihapus")
        bagian.append(
            f"{jumlah_spasi_awal} spasi di awal teks sebelum kata '{kata_awal(teks_sebelum)}' dihapus"
        )

    if jumlah_spasi_akhir > 0:
        perubahan.append("spasi akhir teks dihapus")
        bagian.append(
            f"{jumlah_spasi_akhir} spasi di akhir teks setelah kata '{kata_akhir(teks_sebelum)}' dihapus"
        )

    if len(perubahan) == 0:
        return "FULL", "Teks berubah setelah strip", "Perubahan terjadi pada spasi awal atau akhir teks"

    return "FULL", "; ".join(perubahan), "; ".join(bagian)

# =========================
# 10. Proses strip
# Input strip dari kolom Hasil Cleansing FULL
# =========================
hasil_strip = df["Hasil Cleansing FULL"].apply(strip_teks)

# =========================
# 11. Buat keterangan perubahan
# =========================
kolom_yang_berubah = []
apa_yang_diubah = []
bagian_yang_diganti = []

for sebelum, sesudah in zip(df["Hasil Cleansing FULL"], hasil_strip):
    kolom, apa, bagian = detail_perubahan_strip(sebelum, sesudah)

    kolom_yang_berubah.append(kolom)
    apa_yang_diubah.append(apa)
    bagian_yang_diganti.append(bagian)

# =========================
# 12. Buat tabel output
# =========================
tabel_strip = pd.DataFrame()

if "No" in df.columns:
    tabel_strip["No"] = df["No"]
else:
    tabel_strip["No"] = range(1, len(df) + 1)

tabel_strip["Kriteria"] = df["KRITERIA"]
tabel_strip["Elemen"] = df["ELEMEN"]
tabel_strip["Deskriptor"] = df["DESKRIPTOR"]
tabel_strip["FULL"] = df["FULL"]
tabel_strip["Hasil Case Folding FULL"] = df["Hasil Case Folding FULL"]
tabel_strip["Hasil Cleansing FULL"] = df["Hasil Cleansing FULL"]
tabel_strip["Hasil Strip FULL"] = hasil_strip
tabel_strip["Kolom yang Berubah"] = kolom_yang_berubah
tabel_strip["Apa yang Diubah"] = apa_yang_diubah
tabel_strip["Bagian yang Diganti"] = bagian_yang_diganti

# =========================
# 13. Ringkasan hasil
# =========================
jumlah_data = len(tabel_strip)

jumlah_strip_berubah = (
    tabel_strip["Hasil Cleansing FULL"].apply(teks_aman)
    != tabel_strip["Hasil Strip FULL"].apply(teks_aman)
).sum()

print("\nHASIL STRIP DATA MATRIK")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah strip:", jumlah_strip_berubah)
print("Jumlah data tidak berubah:", jumlah_data - jumlah_strip_berubah)
print("Input strip diambil dari kolom: Hasil Cleansing FULL")

# =========================
# 14. Preview tabel
# =========================
display(
    tabel_strip.head(10).style
    .set_caption("Tabel Hasil Preprocessing Data Matrik Tahap Strip")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 15. Simpan ke CSV
# =========================
output_file = "stripmatrik.csv"

tabel_strip.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 16. Download CSV
# =========================
files.download(output_file)

Saving matrik.xlsx to matrik (6).xlsx
Kolom dalam file:
['KRITERIA', 'ELEMEN', 'DESKRIPTOR', 'FULL']

HASIL STRIP DATA MATRIK
Jumlah data: 75
Jumlah data berubah setelah strip: 0
Jumlah data tidak berubah: 75
Input strip diambil dari kolom: Hasil Cleansing FULL

File CSV berhasil dibuat: stripmatrik.csv

In [10]:
import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display

# =========================
# 1. Upload file data matrik
# Bisa upload data asli atau file hasil strip
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 2. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 3. Kolom wajib data matrik
# =========================
kolom_wajib = [
    "KRITERIA", # Corrected from 'Kriteria'
    "ELEMEN",   # Corrected from 'Elemen'
    "DESKRIPTOR", # Corrected from 'Deskriptor'
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file matrik kamu.")

# =========================
# 4. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 5. Case Folding
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

if "Hasil Case Folding FULL" not in df.columns:
    df["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 6. Cleansing
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

if "Hasil Cleansing FULL" not in df.columns:
    df["Hasil Cleansing FULL"] = df["Hasil Case Folding FULL"].apply(cleansing)

# =========================
# 7. Strip
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

if "Hasil Strip FULL" not in df.columns:
    df["Hasil Strip FULL"] = df["Hasil Cleansing FULL"].apply(strip_teks)

# =========================
# 8. Ambil konteks kata sebelum dan sesudah
# =========================
def ambil_konteks(teks, start, end):
    sebelum = teks[:start]
    sesudah = teks[end:]

    kata_sebelum = re.findall(r"\b\w+\b", sebelum)
    kata_sesudah = re.findall(r"\b\w+\b", sesudah)

    kata_kiri = kata_sebelum[-1] if len(kata_sebelum) > 0 else "awal teks"
    kata_kanan = kata_sesudah[0] if len(kata_sesudah) > 0 else "akhir teks"

    return kata_kiri, kata_kanan

# =========================
# 9. Punctuation Removal
# Menghapus:
# - titik koma ;
# - titik . hanya di akhir kalimat terakhir / akhir teks
#
# Tidak menghapus:
# - titik dua :
# - titik di tengah teks
# =========================
def punctuation_removal(teks):
    teks = teks_aman(teks)

    # Hapus titik koma
    teks = teks.replace(";", " ")

    # Hapus titik hanya di akhir teks
    teks = re.sub(r"\.+\s*$", "", teks)

    # Rapikan spasi
    teks = re.sub(r"\s+", " ", teks).strip()

    return teks

# =========================
# 10. Detail perubahan punctuation removal
# =========================
def detail_perubahan_punctuation(teks_sebelum, teks_sesudah):
    teks_sebelum = teks_aman(teks_sebelum)
    teks_sesudah = teks_aman(teks_sesudah)

    if teks_sebelum == teks_sesudah:
        return "Tidak ada", "Tidak ada perubahan", "Tidak ada perubahan"

    jenis_perubahan = []
    bagian_diganti = []

    # Cek titik koma ;
    for match in re.finditer(r";", teks_sebelum):
        kiri, kanan = ambil_konteks(teks_sebelum, match.start(), match.end())

        if "titik koma dihapus" not in jenis_perubahan:
            jenis_perubahan.append("titik koma dihapus")

        bagian_diganti.append(
            f"titik koma ';' setelah kata '{kiri}' sebelum kata '{kanan}' dihapus"
        )

    # Cek titik di akhir kalimat terakhir / akhir teks
    match_titik_akhir = re.search(r"\.+\s*$", teks_sebelum)

    if match_titik_akhir:
        kiri, kanan = ambil_konteks(
            teks_sebelum,
            match_titik_akhir.start(),
            match_titik_akhir.end()
        )

        jumlah_titik = match_titik_akhir.group().count(".")

        if "titik di akhir kalimat terakhir dihapus" not in jenis_perubahan:
            jenis_perubahan.append("titik di akhir kalimat terakhir dihapus")

        bagian_diganti.append(
            f"{jumlah_titik} titik '.' setelah kata '{kiri}' di akhir teks dihapus"
        )

    if len(jenis_perubahan) == 0:
        return "FULL", "Teks berubah setelah punctuation removal", "Perubahan terjadi pada tanda baca"

    return "FULL", "; ".join(jenis_perubahan), "; ".join(bagian_diganti)

# =========================
# 11. Proses punctuation removal
# Input dari kolom Hasil Strip FULL
# =========================
hasil_punctuation = df["Hasil Strip FULL"].apply(punctuation_removal)

# =========================
# 12. Buat keterangan perubahan
# =========================
kolom_yang_berubah = []
apa_yang_diubah = []
bagian_yang_diganti = []

for sebelum, sesudah in zip(df["Hasil Strip FULL"], hasil_punctuation):
    kolom, apa, bagian = detail_perubahan_punctuation(sebelum, sesudah)

    kolom_yang_berubah.append(kolom)
    apa_yang_diubah.append(apa)
    bagian_yang_diganti.append(bagian)

# =========================
# 13. Buat tabel output
# =========================
tabel_punctuation = pd.DataFrame()

if "No" in df.columns:
    tabel_punctuation["No"] = df["No"]
else:
    tabel_punctuation["No"] = range(1, len(df) + 1)

tabel_punctuation["Kriteria"] = df["KRITERIA"] # Corrected to 'KRITERIA'
tabel_punctuation["Elemen"] = df["ELEMEN"]     # Corrected to 'ELEMEN'
tabel_punctuation["Deskriptor"] = df["DESKRIPTOR"] # Corrected to 'DESKRIPTOR'
tabel_punctuation["FULL"] = df["FULL"]
tabel_punctuation["Hasil Case Folding FULL"] = df["Hasil Case Folding FULL"]
tabel_punctuation["Hasil Cleansing FULL"] = df["Hasil Cleansing FULL"]
tabel_punctuation["Hasil Strip FULL"] = df["Hasil Strip FULL"]
tabel_punctuation["Hasil Punctuation Removal FULL"] = hasil_punctuation
tabel_punctuation["Kolom yang Berubah"] = kolom_yang_berubah
tabel_punctuation["Apa yang Diubah"] = apa_yang_diubah
tabel_punctuation["Bagian yang Diganti"] = bagian_yang_diganti

# =========================
# 14. Ringkasan hasil
# =========================
jumlah_data = len(tabel_punctuation)

jumlah_punctuation_berubah = (
    tabel_punctuation["Hasil Strip FULL"].apply(teks_aman)
    != tabel_punctuation["Hasil Punctuation Removal FULL"].apply(teks_aman)
).sum()

print("\nHASIL PUNCTUATION REMOVAL DATA MATRIK")
print("Jumlah data:", jumlah_data)
print("Jumlah data berubah setelah punctuation removal:", jumlah_punctuation_berubah)
print("Jumlah data tidak berubah:", jumlah_data - jumlah_punctuation_berubah)
print("Yang dihapus: titik koma ';' dan titik '.' di akhir kalimat terakhir")
print("Yang tidak dihapus: titik dua ':' dan titik di tengah teks")

# =========================
# 15. Preview tabel
# =========================
display(
    tabel_punctuation.head(10).style
    .set_caption("Tabel Hasil Preprocessing Data Matrik Tahap Punctuation Removal")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 16. Simpan ke CSV
# =========================
output_file = "punctuationremovalmatrik.csv"

tabel_punctuation.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 17. Download CSV
# =========================
files.download(output_file)

Saving matrik.xlsx to matrik (8).xlsx
Kolom dalam file:
['KRITERIA', 'ELEMEN', 'DESKRIPTOR', 'FULL']

HASIL PUNCTUATION REMOVAL DATA MATRIK
Jumlah data: 75
Jumlah data berubah setelah punctuation removal: 0
Jumlah data tidak berubah: 75
Yang dihapus: titik koma ';' dan titik '.' di akhir kalimat terakhir
Yang tidak dihapus: titik dua ':' dan titik di tengah teks

File CSV berhasil dibuat: punctuationremovalmatrik.csv

In [12]:
# =========================
# 1. Install library
# =========================
!pip install transformers -q

import pandas as pd
import re
import html
from google.colab import files
from IPython.display import display
from transformers import AutoTokenizer

# =========================
# 2. Upload file data matrik
# Disarankan upload: 04_punctuation_removal_data_matrik.csv
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 3. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 4. Kolom wajib data matrik
# =========================
kolom_wajib = [
    "KRITERIA",
    "ELEMEN",
    "DESKRIPTOR",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file matrik kamu.")

# =========================
# 5. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 6. Case Folding
# Jika kolom belum ada, dibuat otomatis
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

if "Hasil Case Folding FULL" not in df.columns:
    df["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 7. Cleansing
# Jika kolom belum ada, dibuat otomatis
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

if "Hasil Cleansing FULL" not in df.columns:
    df["Hasil Cleansing FULL"] = df["Hasil Case Folding FULL"].apply(cleansing)

# =========================
# 8. Strip
# Jika kolom belum ada, dibuat otomatis
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

if "Hasil Strip FULL" not in df.columns:
    df["Hasil Strip FULL"] = df["Hasil Cleansing FULL"].apply(strip_teks)

# =========================
# 9. Punctuation Removal
# Jika kolom belum ada, dibuat otomatis
# Menghapus:
# - titik koma ;
# - titik . hanya di akhir teks
# =========================
def punctuation_removal(teks):
    teks = teks_aman(teks)

    teks = teks.replace(";", " ")
    teks = re.sub(r"\.+\s*$", "", teks)
    teks = re.sub(r"\s+", " ", teks).strip()

    return teks

if "Hasil Punctuation Removal FULL" not in df.columns:
    df["Hasil Punctuation Removal FULL"] = df["Hasil Strip FULL"].apply(punctuation_removal)

# =========================
# 10. Load tokenizer IndoBERT
# =========================
tokenizer = AutoTokenizer.from_pretrained("indobenchmark/indobert-base-p1")

# =========================
# 11. Tokenisasi IndoBERT
# Menggunakan:
# - [CLS] di awal
# - [SEP] di akhir
# - pemisah token menggunakan koma
# =========================
def tokenisasi_indobert(teks):
    teks = teks_aman(teks)

    encoded = tokenizer.encode(
        teks,
        add_special_tokens=True,
        truncation=True,
        max_length=512
    )

    tokens = tokenizer.convert_ids_to_tokens(encoded)

    return ", ".join(tokens)

# =========================
# 12. Proses tokenisasi
# Input dari Hasil Punctuation Removal FULL
# =========================
hasil_tokenisasi = df["Hasil Punctuation Removal FULL"].apply(tokenisasi_indobert)

# =========================
# 13. Buat tabel output
# =========================
tabel_tokenisasi = pd.DataFrame()

if "No" in df.columns:
    tabel_tokenisasi["No"] = df["No"]
else:
    tabel_tokenisasi["No"] = range(1, len(df) + 1)

tabel_tokenisasi["Kriteria"] = df["KRITERIA"] # Corrected to 'KRITERIA'
tabel_tokenisasi["Elemen"] = df["ELEMEN"]     # Corrected to 'ELEMEN'
tabel_tokenisasi["Deskriptor"] = df["DESKRIPTOR"] # Corrected to 'DESKRIPTOR'
tabel_tokenisasi["FULL"] = df["FULL"]
tabel_tokenisasi["Hasil Case Folding FULL"] = df["Hasil Case Folding FULL"]
tabel_tokenisasi["Hasil Cleansing FULL"] = df["Hasil Cleansing FULL"]
tabel_tokenisasi["Hasil Strip FULL"] = df["Hasil Strip FULL"]
tabel_tokenisasi["Hasil Punctuation Removal FULL"] = df["Hasil Punctuation Removal FULL"]
tabel_tokenisasi["Tokenisasi IndoBERT FULL"] = hasil_tokenisasi

# =========================
# 14. Ringkasan hasil
# =========================
print("\nHASIL TOKENISASI INDOBERT DATA MATRIK")
print("Jumlah data:", len(tabel_tokenisasi))
print("Tokenizer: indobenchmark/indobert-base-p1")
print("Token khusus yang digunakan: [CLS] dan [SEP]")
print("Input tokenisasi dari kolom: Hasil Punctuation Removal FULL")

# =========================
# 15. Preview tabel
# =========================
display(
    tabel_tokenisasi.head(10).style
    .set_caption("Tabel Hasil Tokenisasi Data Matrik Menggunakan IndoBERT")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 16. Simpan ke CSV
# =========================
output_file = "tokenisasimatrik.csv"

tabel_tokenisasi.to_csv(
    output_file,
    index=False,
    encoding="utf-8-sig"
)

print("\nFile CSV berhasil dibuat:", output_file)

# =========================
# 17. Download CSV
# =========================
files.download(output_file)

Saving matrik.xlsx to matrik (10).xlsx
Kolom dalam file:
['KRITERIA', 'ELEMEN', 'DESKRIPTOR', 'FULL']

HASIL TOKENISASI INDOBERT DATA MATRIK
Jumlah data: 75
Tokenizer: indobenchmark/indobert-base-p1
Token khusus yang digunakan: [CLS] dan [SEP]
Input tokenisasi dari kolom: Hasil Punctuation Removal FULL

File CSV berhasil dibuat: tokenisasimatrik.csv

In [14]:
# =========================
# 1. Install library
# =========================
!pip install transformers -q

import pandas as pd
import re
import html
import torch
import numpy as np
from google.colab import files
from IPython.display import display
from transformers import AutoTokenizer, AutoModel

# =========================
# 2. Upload file data matrik
# Disarankan upload: 05_tokenisasi_indobert_data_matrik.csv
# =========================
uploaded = files.upload()
file_name = list(uploaded.keys())[0]

# =========================
# 3. Baca file Excel / CSV
# =========================
if file_name.endswith(".csv"):
    df = pd.read_csv(file_name)
else:
    df = pd.read_excel(file_name)

print("Kolom dalam file:")
print(df.columns.tolist())

# =========================
# 4. Kolom wajib data matrik
# =========================
kolom_wajib = [
    "KRITERIA",
    "ELEMEN",
    "DESKRIPTOR",
    "FULL"
]

for kolom in kolom_wajib:
    if kolom not in df.columns:
        raise ValueError(f"Kolom '{kolom}' tidak ditemukan. Cek nama kolom di file matrik kamu.")

# =========================
# 5. Fungsi teks aman
# =========================
def teks_aman(teks):
    if pd.isna(teks):
        return ""
    return str(teks)

# =========================
# 6. Case Folding
# Jika kolom belum ada, dibuat otomatis
# =========================
def case_folding(teks):
    teks = teks_aman(teks)
    return teks.lower()

if "Hasil Case Folding FULL" not in df.columns:
    df["Hasil Case Folding FULL"] = df["FULL"].apply(case_folding)

# =========================
# 7. Cleansing
# Jika kolom belum ada, dibuat otomatis
# =========================
def cleansing(teks):
    teks = teks_aman(teks)

    teks = html.unescape(teks)
    teks = teks.replace("\xa0", " ")
    teks = teks.replace("\n", " ")
    teks = teks.replace("\r", " ")
    teks = teks.replace("\t", " ")
    teks = re.sub(r"\s+", " ", teks)

    return teks

if "Hasil Cleansing FULL" not in df.columns:
    df["Hasil Cleansing FULL"] = df["Hasil Case Folding FULL"].apply(cleansing)

# =========================
# 8. Strip
# Jika kolom belum ada, dibuat otomatis
# =========================
def strip_teks(teks):
    teks = teks_aman(teks)
    return teks.strip()

if "Hasil Strip FULL" not in df.columns:
    df["Hasil Strip FULL"] = df["Hasil Cleansing FULL"].apply(strip_teks)

# =========================
# 9. Punctuation Removal
# Jika kolom belum ada, dibuat otomatis
# Menghapus:
# - titik koma ;
# - titik . hanya di akhir teks
# =========================
def punctuation_removal(teks):
    teks = teks_aman(teks)

    teks = teks.replace(";", " ")
    teks = re.sub(r"\.+\s*$", "", teks)
    teks = re.sub(r"\s+", " ", teks).strip()

    return teks

if "Hasil Punctuation Removal FULL" not in df.columns:
    df["Hasil Punctuation Removal FULL"] = df["Hasil Strip FULL"].apply(punctuation_removal)

# =========================
# 10. Load tokenizer dan model IndoBERT
# =========================
model_name = "indobenchmark/indobert-base-p1"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

print("Device yang digunakan:", device)

# =========================
# 11. Tokenisasi IndoBERT untuk tampilan tabel
# Menggunakan [CLS] dan [SEP]
# =========================
def tokenisasi_indobert(teks):
    teks = teks_aman(teks)

    encoded = tokenizer.encode(
        teks,
        add_special_tokens=True,
        truncation=True,
        max_length=512
    )

    tokens = tokenizer.convert_ids_to_tokens(encoded)

    return ", ".join(tokens)

if "Tokenisasi IndoBERT FULL" not in df.columns:
    df["Tokenisasi IndoBERT FULL"] = df["Hasil Punctuation Removal FULL"].apply(tokenisasi_indobert)

# =========================
# 12. Ekstraksi fitur teks menggunakan IndoBERT
# Output: vektor embedding dari token [CLS]
# =========================
def ekstraksi_embedding_batch(teks_list, batch_size=8):
    semua_embedding = []

    for i in range(0, len(teks_list), batch_size):
        batch_teks = teks_list[i:i + batch_size]

        inputs = tokenizer(
            batch_teks,
            return_tensors="pt",
            add_special_tokens=True,
            truncation=True,
            padding=True,
            max_length=512
        )

        inputs = {key: value.to(device) for key, value in inputs.items()}

        with torch.no_grad():
            outputs = model(**inputs)

        # Ambil embedding token [CLS]
        cls_embedding = outputs.last_hidden_state[:, 0, :]

        semua_embedding.append(cls_embedding.cpu().numpy())

    semua_embedding = np.vstack(semua_embedding)

    return semua_embedding

# =========================
# 13. Proses ekstraksi fitur
# Input dari Hasil Punctuation Removal FULL
# =========================
teks_input = df["Hasil Punctuation Removal FULL"].apply(teks_aman).tolist()

embedding_array = ekstraksi_embedding_batch(teks_input, batch_size=8)

# Ubah embedding menjadi string agar bisa dilihat di CSV
embedding_string = [
    ", ".join([str(round(nilai, 6)) for nilai in vector])
    for vector in embedding_array
]

# =========================
# 14. Buat tabel output
# =========================
tabel_embedding = pd.DataFrame()

if "No" in df.columns:
    tabel_embedding["No"] = df["No"]
else:
    tabel_embedding["No"] = range(1, len(df) + 1)

tabel_embedding["Kriteria"] = df["KRITERIA"]
tabel_embedding["Elemen"] = df["ELEMEN"]
tabel_embedding["Deskriptor"] = df["DESKRIPTOR"]
tabel_embedding["FULL"] = df["FULL"]
tabel_embedding["Hasil Case Folding FULL"] = df["Hasil Case Folding FULL"]
tabel_embedding["Hasil Cleansing FULL"] = df["Hasil Cleansing FULL"]
tabel_embedding["Hasil Strip FULL"] = df["Hasil Strip FULL"]
tabel_embedding["Hasil Punctuation Removal FULL"] = df["Hasil Punctuation Removal FULL"]
tabel_embedding["Tokenisasi IndoBERT FULL"] = df["Tokenisasi IndoBERT FULL"]
tabel_embedding["Vektor Embedding IndoBERT FULL"] = embedding_string
tabel_embedding["Dimensi Embedding"] = embedding_array.shape[1]

# =========================
# 15. Ringkasan hasil
# =========================
print("\nHASIL EKSTRAKSI FITUR TEKS DATA MATRIK")
print("Jumlah data:", len(tabel_embedding))
print("Model:", model_name)
print("Representasi embedding yang digunakan: token [CLS]")
print("Dimensi embedding:", embedding_array.shape[1])
print("Bentuk array embedding:", embedding_array.shape)

# =========================
# 16. Preview tabel
# =========================
display(
    tabel_embedding.head(5).style
    .set_caption("Tabel Hasil Ekstraksi Fitur Teks Data Matrik Menggunakan IndoBERT")
    .set_properties(**{
        "text-align": "left",
        "white-space": "pre-wrap",
        "border": "1px solid black"
    })
    .set_table_styles([
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("background-color", "#d9eaf7"),
                ("border", "1px solid black")
            ]
        },
        {
            "selector": "caption",
            "props": [
                ("caption-side", "top"),
                ("font-weight", "bold"),
                ("font-size", "14px")
            ]
        }
    ])
    .hide(axis="index")
)

# =========================
# 17. Simpan hasil ke CSV
# =========================
output_csv = "06_ekstraksi_fitur_indobert_data_matrik.csv"

tabel_embedding.to_csv(
    output_csv,
    index=False,
    encoding="utf-8-sig"
)

# =========================
# 18. Simpan embedding asli ke NPY
# File ini dipakai untuk cosine similarity
# =========================
output_npy = "ekstraksifiturmatrik.npy"

np.save(output_npy, embedding_array)

print("\nFile CSV berhasil dibuat:", output_csv)
print("File embedding NPY berhasil dibuat:", output_npy)

# =========================
# 19. Download file
# =========================
files.download(output_csv)
files.download(output_npy)

Saving matrik.xlsx to matrik (12).xlsx
Kolom dalam file:
['KRITERIA', 'ELEMEN', 'DESKRIPTOR', 'FULL']

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Device yang digunakan: cpu

HASIL EKSTRAKSI FITUR TEKS DATA MATRIK
Jumlah data: 75
Model: indobenchmark/indobert-base-p1
Representasi embedding yang digunakan: token [CLS]
Dimensi embedding: 768
Bentuk array embedding: (75, 768)

File CSV berhasil dibuat: 06_ekstraksi_fitur_indobert_data_matrik.csv
File embedding NPY berhasil dibuat: ekstraksifiturmatrik.npy